---
- name: Deploy Spring API
  hosts: localhost
  connection: local

  tasks:
    - name: Deploy to Docker Swarm
      docker_stack:
        name: "spring-api"
        state: present
        compose:
          - version: "3.7"
            services:
              spring-api:
                image: spring-api:latest
                restart: always
                environment:
                  - SPRING_PROFILES_ACTIVE={{ lookup('env', 'SPRING_PROFILES_ACTIVE') }}
                ports:
                  - "8080:8080"
        resolve_image: always
